name : Node Continuous Integration

on: 
  pull_request : 
      branches : [ master ]


jobs:
  test_pull_request: 
      runs-on: ubuntu-latest
      steps: 
        - uses: action/checkout@v2
          with:
            node-version: 12
          - run: npm install
          - run: npm test
          - run: npm run build
          